## 异常

### **概述**

```java
try一类语句是对异常进行捕获
throw一类语句是对异常进行声明
两者的目的都是为了将异常抛出
```

程序在运行时出现的不正常情况.

java对不正常情况进行描述后的对象体现.

**问题划分**:

- 严重类问题用Error类来描述
- 非严重类(警告)用Exception类来描述      异常

Throwable类是Error和Exception的父类

### **异常的种类**

```java
输入输出异常：IOException
算术异常类：ArithmeticExecption
空指针异常类：NullPointerException
类型强制转换异常：ClassCastException
操作数据库异常：SQLException
文件未找到异常：FileNotFoundException
数组负下标异常：NegativeArrayException
数组下标越界异常：ArrayIndexOutOfBoundsException
违背安全原则异常：SecturityException
文件已结束异常：EOFException
字符串转换为数字异常：NumberFormatException
方法未找到异常：NoSuchMethodException
```

1. 非检查异常(Error和RuntimeException以及他们的子类)这类问题编译时不会提示和发现,可以用try...catch..finally处理,也可以不做处理.对于这些异常，我们应该修正代码，而不是去通过异常处理器处理 。这样的异常发生的原因多半是代码写的有问题。

   ```java
   数组索引越界ArrayIndexOutOfBoundsException;
   错误的强制类型转换错误ClassCastException;
   除0错误ArithmeticException;
   使用了空对象NullPointerException
   ```

2. 检查异常(除了Error和RuntimeException以及他们的子类其他异常)这类异常要求在方法中要么用try-catch语句捕获它并处理，要么用throws语句声明抛出它，否则编译不会通过。

   ```java
   SQLException ,数据库异常
   IOException,
   ClassNotFoundException 
   ```

### **异常处理**

#### 两种处理方式

##### 第一种捕获异常

这种处理方式是为了防止程序可能出现的异常

```java
try{}catch{}finally{}
```

格式:

```java
try
{
    需要被检测的代码;//若无异常则不会运行catch语句,若前一句代码出现异常,后面的语句不					会再被运行
}
catch(异常类 变量)//catch中应该写有针对性的处理方法
{
    处理异常的代码;(处理方式)
    System.exit(0);//系统退出,jvm结束运行.(finally中的语句不会运行)
}
finally//一定会被执行的代码,通常存放的是释放调用资源的代码
{
    一定会执行的语句;
}
```

输出异常的常用方法:

- ```java
  方法
  getMessage();//异常信息
  toString();
  printStackTrace();//jvm默认调用的就是这个方法
  ```

##### 第二种抛出异常

throws在代码处捕获的异常,在调用方法处捕获处理

 **异常的重写**

1. 子类在重写父类时,如果父类的方法抛出异常,那么子类的重写方法,只能抛出父类的异常或者该异常的子类.

2. 如果父类方法抛出多个异常,那么子类在重写该方法时,只能抛出父类异常的子集.

3. 如果父类或者接口的方法中没有抛出异常,那么子类在重写方法时,也不可以抛出异常.

   如果子类方法出现了异常,就必须要进行try处理,绝对不能抛出异常.

#### **多异常的处理**(可有可无)

- 声明异常时，建议声明**更为具体**的异常。这样处理的可以更具体。

- 对方声明几个异常，就对应有几个catch块。不要定义多余的catch块。

  如果多个catch块中的异常出现继承关系，*父类异常catch块放在最下面。*

```java
class Demo {
    int div(int a,int b)throws ArithmeticException,ArrayIndexOutOfBoundsException {
        int[] arr = new int [a];
        System.out.println(arr[4]);
        return a/b;
    }
}
class ExceptionDemo {
    public static void main(String[] args) {
        Demo x = new Demo();
        try {
            int result = x.div(5,0);
            System.out.println(result);
        } catch (ArithmeticException e) {
            System.out.println(e.toString());
            System.out.println("除零了");
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println(e.toString());
            System.out.println("角标越界了");
        } catch (Exception e){
            System.out.println("其他异常");
        }
        System.out.println("over");
    }
}
```

#### 自定义异常(不常用)

必须是自定义类继承Exception.

继承Exception的原因:

异常类和异常对象都被抛出，都具备可抛性的特点。

可抛性是Throwable这个体系的特点，只有Throwable这个体系的类和对象才可以被throws和throw操作。

优点:将异常看成对象进行封装.

```java
class FushuException extends Exception {
    FushuException(String message) {
        super(message);
    }
}
class Demo {
    int div(int a,int b)throws FushuException {
        if(b<0)
            throw new FushuException("/by fushu");
        return a/b;
    }
}
class ExceptionDemo2 {
    public static void main(String[] args) {
        Demo x = new Demo();
        try {
            int result = x.div(4,-1);
            System.out.println(result);
        } catch(FushuException e) {
            System.out.println(e.toString());
            System.out.println("除数为负数");
        }
    }
}

```

#### **特殊异常RuntimeException(运行时异常)**

Exception中有一个特殊的子类异常:RuntimeException

如果在函数内容抛出该异常,函数上可以不用声明,编译一样通过.

不声明的原因:不需要让调用者处理.当该异常发生时,希望程序停掉.

如果在函数上声明了该异常,调用者可以不用进行处理,编译一样通过.

### throw和throws的区别

```java
throw语句用在方法体内，表示抛出异常，由方法体内的语句处理。
throw是具体向外抛异常的动作，所以它是抛出一个异常实例。
throw的话，那就是你把那个倾向变成真实的了。
```

```java
throws语句用在方法声明后面，表示再抛出异常，由该方法的调用者来处理。
throws主要是声明这个方法会抛出这种类型的异常，使它的调用者知道要捕获这个异常。
throws说明你有那个可能，倾向。
```

```java
1、throws出现在方法函数头；而throw出现在函数体。
2、throws表示出现异常的一种可能性，并不一定会发生这些异常；throw则是抛出了异常，执行throw则一定抛出了某种异常。
3、两者都是消极处理异常的方式（这里的消极并不是说这种方式不好），只是抛出或者可能抛出异常，但是不会由函数去处理异常，真正的处理异常由函数的上层调用处理。
```


